import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import packageJson from "../../package.json"; // Import package.json

import { Toaster } from "react-hot-toast";

import ThemeToggle from "./components/ThemeToggle";
import ThemeProvider from "./components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "fire-next-i Adam & Isak, testa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-white dark:bg-[#191919] text-[#37352f] dark:text-[#ffffffcf]">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
             <div className="flex flex-col min-h-screen"> {/* Added flex and min-h-screen here */}
          <Navbar />
          <main className="flex-grow min-h-screen">{children}</main>

          <Toaster />

          <footer className=" text-center py-4 text-gray-600 dark:text-gray-400 bg-white dark:bg-gray-800">
            Version: {packageJson.version} {/* sticky bottom-0 */}
          </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
